Insults
cs-23-sw-1-p1-17/ChargepointPlacementFinder pull request #1
Opened 2023-10-24 18:51 UTC by Naitsabot

2023-10-24 18:57 UTC, krestenlaust requested changes
LBTM

2023-10-24 18:57 UTC, krestenlaust commented on src/insult
> +that you are also ugly :)
Too unkind
```suggestion
that you are pretty!
```

2023-10-24 18:57 UTC, krestenlaust commented on src/Superdupercprogram.h
> +int poop = 1;
This value should be 3. Trust me bro
```suggestion
int poop = 3;
```

2023-10-24 18:57 UTC, krestenlaust commented on src/Superdupercprogram.cpp
> +    cout << "poop is equal to " << poop;
Vi foretrækker printf... eller noget (manglede noget at review)
```suggestion
#include <stdio>
#include "Superdupercprogram.h"


int main() {
    printf("poop is equal to %d", poop);
```

2023-10-25 09:56 UTC, krestenlaust approved these changes

2023-10-27 09:27 UTC, pSlessing approved these changes
yup yup, kan ikke lide cout tho, the noget c++ møg, pls fix

2023-11-13 09:47 UTC, krestenlaust commented on src/Superdupercprogram.cpp
> +    cout << "poop is equal to " << poop;
```suggestion
#include <iostream>

int main() {
    int poop = 2;
    cout << "poop is equal to " << poop;
```

2023-11-13 09:49 UTC, krestenlaust commented on src/Superdupercprogram.h
> +#endif //SEM_PROJ_1_SUPERDUPERCPROGRAM_H
```suggestion
#ifndef SEM_PROJ_1_SUPERDUPERCPROGRAM_H
#define SEM_PROJ_1_SUPERDUPERCPROGRAM_C

#endif //SEM_PROJ_1_SUPERDUPERCPROGRAM_H
```

2023-11-13 09:49 UTC, closed without merging