print_function for printing the result
cs-23-sw-1-p1-17/ChargepointPlacementFinder pull request #36
Opened 2023-12-06 09:29 UTC by MalleGJ

2023-12-08 09:16 UTC, krestenlaust commented
Jeg har et par kommentarer, men jeg hører lige Anders (@Drude2711 ) og Sebastian (@Naitsabot ) om feedback først

2023-12-08 12:05 UTC, krestenlaust commented on src/print_function.c
> +    for (int i = 0; i<length_of_solution_nodes; i++)
Ja tak 👌

2023-12-08 12:11 UTC, Drude2711 approved these changes

2023-12-08 12:26 UTC, krestenlaust requested changes
Alt i alt godt lavet! Så fik du lavet lidt kode alligevel :P

Der er bare lidt formaliteter og tre enkelte memory leaks. Jeg har rettet det hele i mine kommentarer @MalleGJ

2023-12-08 12:26 UTC, krestenlaust commented on src/main.c
> +
I missede et memory leak :P
```suggestion

free(nodes);
free(edges);
free(solution_nodes);
```

2023-12-08 12:26 UTC, krestenlaust commented on src/print_function.c
> +
```suggestion
```

2023-12-08 12:26 UTC, krestenlaust commented on src/print_function.c
> +        printf("%6d. | %5d%2c | %11d\n", i+1, solution_nodes[i].node_ID, ' ', solution_nodes[i].total_traffic_attracted);
Uforklaret tilfældigt mellemrum?

Spacing :)
```suggestion
        printf("%6d. | %5d%2c | %11d\n", i + 1, solution_nodes[i].node_ID, ' ', solution_nodes[i].total_traffic_attracted);
```

2023-12-08 12:26 UTC, krestenlaust commented on src/main.c
> +
```suggestion
```

2023-12-08 12:26 UTC, krestenlaust commented on src/print_function.h
> +#include "algorithm_functions.h"
```suggestion
#include "algorithm_functions.h"

```

2023-12-11 10:14 UTC, krestenlaust approved these changes
LGTM, merge burde heller ikke være noget problem for nu. @MalleGJ du merger bare når du er klar

2023-12-11 12:01 UTC, merged